### PR TITLE
Load users data on plugin runtime enabling

### PR DESCRIPTION
**Pull request by danirod12**
Comments inside commit are reach to explain what I want.
The problem is that users wont be loaded if plugin was enabled/reloaded using PlugMan

### CODE REVIEW

**Review by DragonMadness — APPROVED** [review]
good change 👍

**Comment by Oribuin** [comment]
I appreciate the pull request and i apologise for being so nit picking about the smallest details

**Review by zhabkazhaba — APPROVED** [review]

**Comment by danirod12** [comment]
When merge? @Oribuin 
Looking for month for such a small pull seems to be strange

**Comment by Oribuin** [comment]
This wasn't originally merged due to fact the requested changes were ignored, although upon further inspection, Using plugins such as plugman to reload eternaltags during runtime is for very obvious reasons not recommended but there are complications that are not fixable within the plugin itself.

The library that is used to make EternalTags, RoseGarden, has a ZipException when loading the locale files with plugman due to the nature of how it loads.  If you want to fix this issue on [RoseGarden's Side](https://github.com/Rosewood-Development/RoseGarden/tree/master/src/main/java/dev/rosewood/rosegarden/locale/provider) I would be happy to return to this PR, but for now im going to close it.

**Comment by danirod12** [comment]
You not requested changes, lol
Better to not work with you at all, so unprofessional

Also we use this fix becuase it solves the problem

**Comment by Oribuin** [comment]
image

you are dense

**Comment by danirod12** [comment]
You started a review, but not finished it LMAO. Do you even know how to use GitHub?
What you can review if you even not know how to finish a review with changes request 😂
Only you see your comments, because review is pending.

Also you were answering like 3 months or how much, do not know what github notifications are?

The only dense with no knowledge here is YOU. Do not insult people in place where you have zero knowledge

image

**Comment by Oribuin** [comment]
okay, that was my fault completely i apologise on that front, genuinely never noticed that once. all my github notifications were turned off for a while hence why it seems like I ignored everything.

I still stand by never merging this due to the ZipException issue

**Pull request closed without merging**
